title: Sid Shankar
description: Engineering Management and Technical Leadership
author:
  name: Sid Shankar
remote_theme: benbalter/retlab
lang: en-US

# Pages to include in header navigation
nav_pages:
  - about.md
  - values.md

# Pages to include in footer navigation
#footer_pages:
#  - books.md

# Links to include on the contact page
contact_links:
  - name: Twitter
    url: https://twitter.com/SidShankar_
    icon: fa-brands fa-twitter
  - name: LinkedIn
    url: https://www.linkedin.com/in/engineer-sid-shankar/
    icon: fa-brands fa-linkedin
  - name: GitHub
    url: https://github.com/sidshank
    icon: fa-brands fa-github

permalink: "/:year/:month/:day/:title/"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false

plugins:
  - jekyll-avatar
  - jekyll-github-metadata
